config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :opinions do
    resources :likes, only: [:create, :destroy]
  end

  resources :followings, only: [:create, :show, :destroy]
  
  resources :users, only: [:index, :show]

  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  

  root 'opinions#index'
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  validates :text, presence: true, length: { maximum: 100,
                                             too_long: '100 characters in opinion is the maximum allowed.' }

  belongs_to :author, class_name: 'User', foreign_key: 'authorid'
  has_many :likes, dependent: :destroy
end

def like_count(opinion)
  @like = Like.where(opinion_id: opinion.id)
  @like.count
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :set_opinion, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /opinions or /opinions.json
  def index
    @opinions = Opinion.all.order('created_at DESC')
    @opinion = Opinion.new
  end

  # GET /opinions/1 or /opinions/1.json
  def show; end

  # GET /opinions/new
  def new
    @opinion = current_user.opinions.build
  end

  # GET /opinions/1/edit
  def edit; end

  # POST /opinions or /opinions.json
  def create
    @opinion = current_user.opinions.build(opinion_params)

    respond_to do |format|
      if @opinion.save
        format.html { redirect_to root_path, notice: 'Opinion was successfully created.' }
        format.json { render :show, status: :created, location: @opinion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opinions/1 or /opinions/1.json
  def update
    respond_to do |format|
      if @opinion.update(opinion_params)
        format.html { redirect_to @opinion, notice: 'Opinion was successfully updated.' }
        format.json { render :show, status: :ok, location: @opinion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opinions/1 or /opinions/1.json
  def destroy
    @opinion.destroy
    respond_to do |format|
      format.html { redirect_to opinions_url, notice: 'Opinion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_opinion
    @opinion = Opinion.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def opinion_params
    params.require(:opinion).permit(:text)
  end
end

app/helpers/opinions_helper.rb
# rubocop:disable Style/GuardClause
module OpinionsHelper
  def like_or_dislike_btn(opinion)
    like = Like.find_by(opinion: opinion, user: current_user)
    if like
      link_to('Likes!', opinion_like_path(id: like.id, opinion_id: opinion.id),
              method: :delete, class: 'text-decoration-none color-grey')
    else
      link_to('Likes!', opinion_likes_path(opinion_id: opinion.id), method: :post,
                                                                    class: 'text-decoration-none color-grey')
    end
  end

  def edit_icon(opinion)
    link_to 'edit', edit_opinion_path(opinion), class: 'text-decoration-none' unless current_user != @user
  end

  def trash_icon(opinion)
    unless current_user != @user
      link_to 'delete', opinion, method: :delete, data: { confirm: 'Are you sure you want to delete this tweet?' }
    end
  end

  def who_to_follow_fullname(user)
    user.fullname if !current_user.followed_users.include?(user) and current_user != user
  end

  def who_to_follow_photo(user)
    profile_photo(user) if !current_user.followed_users.include?(user) and current_user != user
  end

  def who_to_follow_button(user)
    if !current_user.followed_users.include?(user) and current_user != user
      button_to 'Follow', follow_user_path(user.id), method: 'POST', class: 'btn btn-primary btn-sm align-self-end'
    end
  end
end
# rubocop:enable Style/GuardClause

app/views/opinions/_form.html.erb
<%= form_with(model: opinion) do |form| %>
  

  <div class="field g-light border pt-3 pb-3 ps-3 ">
    <%= form.label :"Say something" %>
    <%= form.text_area :text, placeholder: "Compose a new opinion", class: "text-area" %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/opinions/_wall.html.erb
<div class='page'>
<div class = "horizontal ps-3 py-2">
    <div class = "pt-3">
        <div class = "container">
            <div class = "row">
              <div class ="col-8">
                <%= render 'form', opinion: @opinion %>
                    <div>
                        <h4 class = "py-4">Recent Opinions</h4>
                            <div>
                                <% @opinions.includes(:author).each do | opinion | %>
                                <div class="d-flex g-light border px-2 py-2 my-1">
                                <div class = "py-2 pe-2">
                                    <%= profile_photo(opinion.author) %>
                                </div>
                                <div>
                                    <div class="fw-bold py-2"><%= link_to "#{opinion.author.username}", user_path(opinion.author), class: "text-decoration-none medium-font" %></div>
                                        <p class = "pb-2 small-font"><%= opinion.text %></p>
                                        <div class='post-liking'>
                                            <span class='post-date'> <%= opinion.created_at.strftime("%Y/%m/%d") %> </span>
                                            <%= like_or_dislike_btn(opinion) %>
                                            <span class = "like_count"><%= like_count(opinion) %></span>
                                        </div>
                                    </div>
                                 </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                    <div class = "col whotofollow">
                        <h3 class = "bold color-grey pb-2">Who to follow</h3>
                        <% User.all.includes(:image_attachment).each do | user | %>
                         <div class = "d-flex pt-2 justify-content-between side justify-content-center">
                            <%= who_to_follow_photo(user) %>
                            <%= who_to_follow_fullname(user) %>
                            <%= who_to_follow_button(user) %>
                         </div>
                            
                        <% end %>
                        
                    
                </div>
            </div>    </div>
        </div>
</div>


</div>

app/views/opinions/edit.html.erb
<div class="horizontal">

    <h1>Editing Opinion</h1>

    <%= render 'form', opinion: @opinion %>

    <%= link_to 'Show', @opinion %> |
    <%= link_to 'Back', opinions_path %>
</div>

app/views/opinions/index.html.erb
<div class ="horizontal">
    <p id="notice"><%= notice %></p>
</div>
<%= render 'wall' %>

app/views/opinions/new.html.erb
<div class = "horizontal">
<p id="notice"><%= notice %></p>


<h1>New Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Back', opinions_path %>
<div>

app/views/opinions/show.html.erb
  <p id="notice"><%= notice %></p>
<div class= "horizontal">
  <p>
    <strong>Text:</strong>
    <%= @opinion.text %>
  </p>
  <%= link_to 'Edit', edit_opinion_path(@opinion) %> |
  <%= link_to 'Back', opinions_path %>
</div>